### **Import Library**

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten
from tensorflow.keras.layers import Conv2D, MaxPooling2D
from tensorflow.keras.utils import to_categorical


### **Load and Prepare Data**

In [ ]:

(X_train, y_train), (X_test, y_test) = mnist.load_data()

X_train = X_train.astype('float32') / 255.0
X_test = X_test.astype('float32') / 255.0

X_train = np.expand_dims(X_train, axis=-1)
X_test = np.expand_dims(X_test, axis=-1)

y_train = to_categorical(y_train, 10)
y_test = to_categorical(y_test, 10)


11490434/11490434 [==============================] - 0s 0us/step


**Build the Model**

In [ ]:
model = Sequential([
    Conv2D(32, kernel_size=(3, 3), activation='relu', input_shape=(28, 28, 1)),
    MaxPooling2D(pool_size=(2, 2)),
    Dropout(0.25),
    Flatten(),
    Dense(128, activation='relu'),
    Dropout(0.5),
    Dense(10, activation='softmax')
])

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 26, 26, 32)        320       
                                                                 
 max_pooling2d (MaxPooling2  (None, 13, 13, 32)        0         
 D)                                                              
                                                                 
 dropout (Dropout)           (None, 13, 13, 32)        0         
                                                                 
 flatten (Flatten)           (None, 5408)              0         
                                                                 
 dense (Dense)               (None, 128)               692352    
                                                                 
 dropout_1 (Dropout)         (None, 128)               0         
                                                        

**Train the Model**

In [ ]:
history = model.fit(X_train, y_train, batch_size=128, epochs=10, validation_split=0.2)


Epoch 1/10
375/375 [==============================] - 28s 75ms/step - loss: 0.0495 - accuracy: 0.9841 - val_loss: 0.0447 - val_accuracy: 0.9874
Epoch 2/10
375/375 [==============================] - 27s 71ms/step - loss: 0.0464 - accuracy: 0.9853 - val_loss: 0.0458 - val_accuracy: 0.9867
Epoch 3/10
375/375 [==============================] - 27s 73ms/step - loss: 0.0454 - accuracy: 0.9856 - val_loss: 0.0480 - val_accuracy: 0.9865
Epoch 4/10
375/375 [==============================] - 26s 70ms/step - loss: 0.0412 - accuracy: 0.9868 - val_loss: 0.0420 - val_accuracy: 0.9878
Epoch 5/10
375/375 [==============================] - 26s 70ms/step - loss: 0.0382 - accuracy: 0.9879 - val_loss: 0.0438 - val_accuracy: 0.9872
Epoch 6/10
375/375 [==============================] - 27s 72ms/step - loss: 0.0359 - accuracy: 0.9879 - val_loss: 0.0451 - val_accuracy: 0.9887
Epoch 7/10
375/375 [==============================] - 28s 75ms/step - loss: 0.0340 - accuracy: 0.9884 - val_loss: 0.0455 - val_accuracy:

**Evaluate the Model**

In [ ]:
score = model.evaluate(X_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

# Confusion matrix and classification report
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true = np.argmax(y_test, axis=1)

print('Confusion Matrix:')
print(confusion_matrix(y_true, y_pred_classes))
print('\nClassification Report:')
print(classification_report(y_true, y_pred_classes))


Test loss: 0.03733320161700249
Test accuracy: 0.9891999959945679
313/313 [==============================] - 2s 6ms/step
Confusion Matrix:
[[ 972    0    2    1    1    0    3    0    1    0]
 [   0 1133    2    0    0    0    0    0    0    0]
 [   1    1 1023    0    1    0    0    4    2    0]
 [   0    0    2 1003    0    2    0    1    2    0]
 [   0    0    0    0  980    0    0    0    0    2]
 [   2    0    0    5    0  881    4    0    0    0]
 [   3    3    0    1    3    2  944    0    2    0]
 [   0    1    7    0    0    0    0 1019    1    0]
 [   2    1    4    4    2    2    0    1  955    3]
 [   2    1    0    6    8    2    0    5    3  982]]

Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       980
           1       0.99      1.00      1.00      1135
           2       0.98      0.99      0.99      1032
           3       0.98      0.99      0.99      1010
           4       0.98      1.00   

**Save the Model**

In [ ]:
model.save('mnist_cnn_model.h5')


/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
